server:
  port: 8001

spring:
  application:
    name: cloud-payment-service   #注册到 eureka 的服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mysql
    password: mysql
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true    #表示是否将自己（该项目、该模块）注册进 Eureka 服务注册中心了,默认为 true。
    fetch-registry: true   #是否从 EurekaServer 抓取已有的注册信息，默认为 true（检索服务）。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #表示注册进 Eureka 的地址。