server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:                                   #路由可以配置多个
        - id: payment_routh                     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001           #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service       #未使用 Eureka 服务注册中心，匹配后提供服务的路由地址:uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/getPaymentById/**   # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001           #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service       #匹配后提供服务的路由地址:uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/lb/**               # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true     #访问路径可以显示IP地址
  client: #服务提供者 provider 注册进 eureka 服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka