spring:
  profiles:
#      active: test # 表示开发环境；配置什么就加载什么。即可实现开发人员的配置文件切换。
#    active: dev # 表示开发环境；配置什么就加载什么。即可实现开发人员的配置文件切换,无缝对接，灵活切换。
    active: info # 表示开发环境；配置什么就加载什么。即可实现开发人员的配置文件切换,无缝对接，灵活切换。